import { ToolInfo } from './types';2
export const TOOLS: ToolInfo[] = [
  {
     title: 'AI Chat',
     sub: 'Smart AI assistant',
     icon: 'Ø=Ü¬',
     bg: 'bg-violet-100 dark:bg-violet-950/40',
     color: 'text-violet-600 dark:text-violet-400',
     route: 'chat',
  },
  {
     title: 'AI Image',
     sub: 'Generate images',
     icon: 'Ø=Ý¼þ',
     bg: 'bg-emerald-100 dark:bg-emerald-950/40',
     color: 'text-emerald-600 dark:text-emerald-400',
     route: 'imagegen',
  },
  {
     title: 'Photo Edit',
     sub: 'Edit your photos',
     icon: ''(',
     bg: 'bg-pink-100 dark:bg-pink-950/40',
     color: 'text-pink-600 dark:text-pink-400',
     route: 'editor',
  },
  {
     title: 'PDF Summarizer',
     sub: 'Summarize any document',
     icon: 'Ø=ÜÄ',
     bg: 'bg-rose-100 dark:bg-rose-950/40',
     color: 'text-rose-600 dark:text-rose-400',
     route: 'chat',
  },
  {
     title: 'AI Writer',
     sub: 'Write blogs or emails',
     icon: ''þ',
     bg: 'bg-amber-100 dark:bg-amber-950/40',
     color: 'text-amber-600 dark:text-amber-400',
     route: 'chat',
  },
  {
     title: 'Translate',
     sub: 'Translate text with AI',
     icon: 'Ø<ß',
     bg: 'bg-blue-100 dark:bg-blue-950/40',
     color: 'text-blue-600 dark:text-blue-400',
     route: 'chat',
  },
  {
     title: 'Voice Assistant',
     sub: 'Talk and listen',
     icon: 'Ø<ß™þ',
     bg: 'bg-indigo-100 dark:bg-indigo-950/40',
     color: 'text-indigo-600 dark:text-indigo-400',
     route: 'chat',
  },
  {
     title: 'AI Code Maker',
     sub: 'Write code snippets',
     icon: 'Ø=Ü»',
     bg: 'bg-cyan-100 dark:bg-cyan-950/40',
     color: 'text-cyan-600 dark:text-cyan-400',
     route: 'chat',
  },
  {
     title: 'Image to Video',
     sub: 'Create beautiful videos',
     icon: 'Ø<ß¬',
     bg: 'bg-purple-100 dark:bg-purple-950/40',
     color: 'text-purple-600 dark:text-purple-400',
     route: 'imagegen',
  },
  {
     title: 'Background Erase',src/data.ts (continued)
      sub: 'Transparent background',
      icon: '+',
      bg: 'bg-orange-100 dark:bg-orange-950/40',
      color: 'text-orange-600 dark:text-orange-400',
      route: 'editor',
   },
   {
      title: 'AI Logo Maker',
      sub: 'Design modern logos',
      icon: 'Ø<ß÷þ',
      bg: 'bg-teal-100 dark:bg-teal-950/40',
      color: 'text-teal-600 dark:text-teal-400',
      route: 'imagegen',
   },
   {
      title: 'HD Upscaler',
      sub: 'Improve quality',
      icon: 'Ø=ÜÐ',
      bg: 'bg-sky-100 dark:bg-sky-950/40',
      color: 'text-sky-600 dark:text-sky-400',
      route: 'editor',
    },
 ];
102      export const IMAGE_STYLES = [
    'Realistic',
    'Anime',
    '3D Render',
    'Digital Art',
    'Sketch',
    'Cinematic',
    'Cyberpunk',
    'Minimalist',
 ];

