import { ToolInfo } from './types';

export const TOOLS: ToolInfo[] = [
  {
    title: 'AI Chat',
    sub: 'Smart AI assistant',
    icon: '💬',
    bg: 'bg-violet-100 dark:bg-violet-950/40',
    color: 'text-violet-600 dark:text-violet-400',
    route: 'chat',
  },
  {
    title: 'AI Image',
    sub: 'Generate images',
    icon: '🖼️',
    bg: 'bg-emerald-100 dark:bg-emerald-950/40',
    color: 'text-emerald-600 dark:text-emerald-400',
    route: 'imagegen',
  },
  {
    title: 'Photo Edit',
    sub: 'Edit your photos',
    icon: '✨',
    bg: 'bg-pink-100 dark:bg-pink-950/40',
    color: 'text-pink-600 dark:text-pink-400',
    route: 'editor',
  },
  {
    title: 'PDF Summarizer',
    sub: 'Summarize any document',
    icon: '📄',
    bg: 'bg-rose-100 dark:bg-rose-950/40',
    color: 'text-rose-600 dark:text-rose-400',
    route: 'chat',
  },
  {
    title: 'AI Writer',
    sub: 'Write blogs or emails',
    icon: '✏️',
    bg: 'bg-amber-100 dark:bg-amber-950/40',
    color: 'text-amber-600 dark:text-amber-400',
    route: 'chat',
  },
  {
    title: 'Translate',
    sub: 'Translate text with AI',
    icon: '🌐',
    bg: 'bg-blue-100 dark:bg-blue-950/40',
    color: 'text-blue-600 dark:text-blue-400',
    route: 'chat',
  },
  {
    title: 'Voice Assistant',
    sub: 'Talk and listen',
    icon: '🎙️',
    bg: 'bg-indigo-100 dark:bg-indigo-950/40',
    color: 'text-indigo-600 dark:text-indigo-400',
    route: 'chat',
  },
  {
    title: 'AI Code Maker',
    sub: 'Write code snippets',
    icon: '💻',
    bg: 'bg-cyan-100 dark:bg-cyan-950/40',
    color: 'text-cyan-600 dark:text-cyan-400',
    route: 'chat',
  },
  {
    title: 'Image to Video',
    sub: 'Create beautiful videos',
    icon: '🎬',
    bg: 'bg-purple-100 dark:bg-purple-950/40',
    color: 'text-purple-600 dark:text-purple-400',
    route: 'imagegen',
  },
  {
    title: 'Background Erase',
    sub: 'Transparent background',
    icon: '⬚',
    bg: 'bg-orange-100 dark:bg-orange-950/40',
    color: 'text-orange-600 dark:text-orange-400',
    route: 'editor',
  },
  {
    title: 'AI Logo Maker',
    sub: 'Design modern logos',
    icon: '🏷️',
    bg: 'bg-teal-100 dark:bg-teal-950/40',
    color: 'text-teal-600 dark:text-teal-400',
    route: 'imagegen',
  },
  {
    title: 'HD Upscaler',
    sub: 'Improve quality',
    icon: '📐',
    bg: 'bg-sky-100 dark:bg-sky-950/40',
    color: 'text-sky-600 dark:text-sky-400',
    route: 'editor',
  },
];

export const IMAGE_STYLES = [
  'Realistic',
  'Anime',
  '3D Render',
  'Digital Art',
  'Sketch',
  'Cinematic',
  'Cyberpunk',
  'Minimalist',
];
